### ISSUE TITLE
Caddy2搭建HTTPS

### ISSUE THREAD

**Issue by hello1983** [hello1983/New_Blog#3]
* 服务端安装Caddy2

```shell
wget -P /usr/bin/ https://starts.sh/cloud/docs/caddy
```

```shell
chmod +x /usr/bin/caddy
```

* 这个时候caddy二进制文件也就下载到/usr/bin/里去了，直接caddy run就可以运行。

* 配置caddy.json文件

```shell
mkdir -p /etc/caddy

cd /etc/caddy

```

```yaml
cat <<EOF > caddy.json
{
    "admin": {"disabled": true},
    "apps": {
        "http": {
            "servers": {
                "srv0": {
                    "listen": [":443"],
                    "logs": {},
                    "routes": [{
                        "handle": [{
                            "handler": "forward_proxy",
                            "hide_ip": true,
                            "hide_via": true,
                            "auth_user": "uname",
                            "auth_pass": "psaaword"
                        }]
                    }, 
                    {
                    "match": [{"host": ["域名"]}],
                    "handle": [{
                        "handler": "file_server",
                        "root": "/var/www/html"
                    }],
                    "terminal": false
                    }],
                    "tls_connection_policies": [{
                        "match": {"sni": ["域名"]}
                    }],
                    "experimental_http3": true,
                    "allow_h2c": true
                }
            }
        },
        "tls": {
            "automation": {
                "policies": [{
                    "subjects": ["域名"],
                    "issuer": {
                        "email": "邮箱",
                        "module": "acme"
                    }
                }]
            }
        }
    }
}
EOF

```

* 检查80端口有没有被其它服务占用，因为caddy需要用80/443端口申请证书，否则会启动失败。下面命令检查端口占用情况：

```shell
netstat -lntp
```

* 上面配置、检查完就可以启动caddy了，启动命令如下：

```shell
caddy run --config /etc/caddy/caddy.json
```

* 注册systemd服务. 新建caddy.service ：

```shell
vi /etc/systemd/system/caddy.service
```

* 添加如下内容

```sh
cat <<EOF > /etc/systemd/system/caddy.service

[Unit]
Description=Caddy
Documentation=https://caddyserver.com/docs/
After=network.target

[Service]
User=root
ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/caddy.json
ExecReload=/usr/bin/caddy reload --config /etc/caddy/caddy.json
TimeoutStopSec=5s
LimitNOFILE=1048576
LimitNPROC=512
PrivateTmp=true
ProtectSystem=full
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
EOF
```

* 重载systemctl服务 

```shell
systemctl daemon-reload
```

* 到这也就可以启动caddy了

```shell
systemctl start caddy #启动

systemctl restart caddy #重启

systemctl status caddy #查看状态

systemctl stop caddy #停止

systemctl enable caddy #添加开机自启动
```
